(setq use-file-dialog nil)
(setq use-dialog-box nil)
(setq inhibit-startup-screen t)
(setq inhibit-startup-echo-area-message t)
(setq indicate-empty-lines t)
(tool-bar-mode -1)
(set-scroll-bar-mode nil)
(global-display-line-numbers-mode)

(provide 'init-gui-config)
